2025-04-04 07:24:53,970 - ERROR - Error generating relationship statistics: Transaction aborted in previous step. Cannot proceed.
Traceback (most recent call last):
  File "C:\fil-relex\backend\dictionary_manager.py", line 11037, in display_leaderboard
    raise Exception("Transaction aborted in previous step. Cannot proceed.")
Exception: Transaction aborted in previous step. Cannot proceed.
